name: Create release
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/checkout@master
      - name: Package
        uses: thedoctor0/zip-release@master
        with:
          filename: 'ctan.zip'
          exclusions: '*.git*'
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ctan.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}